### ISSUE TITLE
Needs Scripting *New MST-like*

### ISSUE THREAD

**Issue by Master-Peace-King** [Gideon9212/Custom_Requests#4]
![visible whirlwind](https://user-images.githubusercontent.com/31558532/29992856-e4946b98-8f73-11e7-864e-3a70a9f92b07.png)
Just needs scripting. please do so.

**Comment by Gideon9212** [comment]
PSCT needs corrected. (Should be then instead of a -. So then if the monster....)
Needs the last part of cards and effects cannot be activated in response removed. This is a weaker version of trap dushshoot, but as a spell, with chain destruction attached to it. :neutral_face: Kinda too strong with that part with it.
