### ISSUE TITLE
Need Script For "Vortex"

### ISSUE THREAD

**Issue by jaydon145** [Gideon9212/Custom_Requests#7]
![image](https://user-images.githubusercontent.com/32945068/31800029-23073ce6-b4fb-11e7-82b5-8827d202a77b.png)

**Comment by Gideon9212** [comment]
Didn't see this until now. o.o
I'm declining due to the fact its a dark hole and a harpie feather duster in one with minimal downsides. (You can still OTK with burn or shutdown a set board and setup your own and lock them out, making what they draw useless)
Needs harder cost to make sure you don't get a plus on the sending.
